name: Robot Framework Parallel CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  split-tests:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List test files
        id: set-matrix
        run: |
          files=$(find tests -name '*.robot' -exec basename {} \;)
          matrix=$(echo $files | jq -R -s -c 'split(" ")')
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

  run-tests:
    needs: split-tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ${{ fromJson(needs.split-tests.outputs.matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Robot tests
        run: |
          pabot --processes 2 tests/${{ matrix.file }}

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robot-results-${{ matrix.file }}
          path: output.xml
